package umariana.cupi2.torneonordico.interfaz;

import umariana.cupi2.torneonordico.mundo.TorneoNordico;
import javax.swing.*;
import java.awt.*;

public class InterfazTorneoNordico extends javax.swing.JFrame {

    private TorneoNordico torneo;
    private PanelArma panelArma;
    private PanelHorda panelHorda;
    private PanelEscenario panelEscenario;
    private PanelHistorial panelHistorial;
    private PanelInventario panelInventario;
    private PanelEstadisticas panelEstadisticas;
    private JButton btnReiniciar;

    // Colores 
    private final Color COLOR_AZUL_FONDO = new Color(20, 30, 60);
    private final Color COLOR_ORO = new Color(212, 175, 55);

    public InterfazTorneoNordico() {
        initComponents();
        torneo = new TorneoNordico();
        inicializarVentana();
        inicializarComponentes();
    }

    private void inicializarVentana() {
        setTitle("Torneo Nórdico - CUPI2 Nivel 3");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 800);
        setLocationRelativeTo(null);
        setResizable(true);
        getContentPane().setBackground(COLOR_AZUL_FONDO);
        setLayout(new BorderLayout());
    }

    private void inicializarComponentes() {
        // Panel superior con título
        JPanel panelTitulo = new JPanel();
        panelTitulo.setBackground(COLOR_AZUL_FONDO);
        JLabel lblTitulo = new JLabel("TORNEO NÓRDICO ️");
        lblTitulo.setForeground(COLOR_ORO);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 24));
        panelTitulo.add(lblTitulo);

        // Panel central con los dos paneles principales
        JPanel panelCentral = new JPanel(new GridLayout(3, 2, 10, 10));
        panelCentral.setBackground(COLOR_AZUL_FONDO);
        panelCentral.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Crear los paneles
        panelArma = new PanelArma(torneo);
        panelEscenario = new PanelEscenario(torneo);
        panelHistorial = new PanelHistorial(torneo);
        panelHorda = new PanelHorda(torneo, panelEscenario, panelHistorial);
        panelInventario = new PanelInventario(torneo);
        panelEstadisticas = new PanelEstadisticas(torneo);

        panelCentral.add(panelArma);
        panelCentral.add(panelEscenario);
        panelCentral.add(panelHorda);
        panelCentral.add(panelHistorial);
        panelCentral.add(panelInventario);
        panelCentral.add(panelEstadisticas);

        // Panel inferior con botón reiniciar
        JPanel panelInferior = new JPanel();
        panelInferior.setBackground(COLOR_AZUL_FONDO);

        btnReiniciar = new JButton("Reiniciar Juego");
        btnReiniciar.setBackground(COLOR_ORO);
        btnReiniciar.setForeground(Color.BLACK);
        btnReiniciar.setFont(new Font("Arial", Font.BOLD, 14));
        btnReiniciar.addActionListener(e -> reiniciarJuego());

        panelInferior.add(btnReiniciar);

        // Agregar componentes a la ventana
        add(panelTitulo, BorderLayout.NORTH);
        add(panelCentral, BorderLayout.CENTER);
        add(panelInferior, BorderLayout.SOUTH);
    }

    private void reiniciarJuego() {
        torneo.reiniciarJuego();
        panelArma.habilitarSeleccion();
        panelEscenario.reiniciarPanel();
        panelHorda.reiniciarPanel();
        panelHistorial.reiniciarPanel();
        panelInventario.reiniciarPanel();
        panelEstadisticas.reiniciarPanel();
        JOptionPane.showMessageDialog(this, "Juego reiniciado. ¡Buena suerte, guerrero!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazTorneoNordico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazTorneoNordico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazTorneoNordico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazTorneoNordico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazTorneoNordico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
